### ISSUE TITLE
Looking for new maintainers for quarkus-hibernate-types extension.

### ISSUE THREAD

**Issue by andrejpetras** [quarkiverse/quarkus-hibernate-types#102]
Hi,

currently, I do not have much time and I do have more open topics (also in `quarkiverse`) in open source communities. I do have a feeling I am not supporting the `quarkus-hibernate-types` extension how I should.

I'm looking for new maintainers to support this extension, implement new features and join the `quarkiverse` community.

BR
Andrej

PS: the implementation must go on

**Comment by wglanzer** [comment]
Hi Andrej,

if you want, I can take over this position very gladly.

My vision of this project was to include the original hybernate-types and make it available for the Quarkus universe, without any big custom implementations around it.
For this it will also be necessary to migrate to hybernate-types 6.0 in the future, when Quarkus uses Hibernate 6.
I still have to look at the support for "reactive" and what that would mean for the hibernate-types. So, I don't have any direct plans or ideas for this yet.

**Comment by andrejpetras** [comment]
Hi @wglanzer, great. 

@gastaldi @gsmet @maxandersen 
Hello guys, how can we do this?
