### ISSUE TITLE
Where to find the release?

### ISSUE THREAD

**Issue by wiradikusuma** [quarkiverse/quarkus-hibernate-types#13]
<dependency>
			<groupId>io.quarkiverse.hibernate</groupId>
			<artifactId>quarkus-hibernate-types</artifactId>
			<version>0.1.0</version>
		</dependency>

Resolution failed. Which repository to use?

**Comment by gsmet** [comment]
The groupId in the README is incorrect. This is the artifact you should use: https://search.maven.org/artifact/io.quarkiverse.hibernatetypes/quarkus-hibernate-types/0.1.0/jar .
