### ISSUE TITLE
Quarkus uses hibernate 6.4 but this lib still depends on hypersistence-utils-hibernate-62

### ISSUE THREAD

**Issue by izogrow** [quarkiverse/quarkus-hibernate-types#197]
Hi Team!

I tried to update my project from quarkus 3.2.9 to 3.7.4 but faced this issue https://hibernate.atlassian.net/browse/HHH-17678

There was an upgrade of Hibernate from 6.2 to 6.4 but this quarkus-hibernate-types lib still depends on the hypersistence-utils-hibernate-62 lib for the hibernate 6.2. Could you upgrade the dependency to hypersistence-utils-hibernate-63 to support the latest quarkus versions?

https://github.com/vladmihalcea/hypersistence-utils?tab=readme-ov-file#hibernate-64-and-63

**Comment by wglanzer** [comment]
Hi @izogrow 

thanks for your update hint.
A new version, ´quarkus-hibernate-types:2.2.0´, was created and will be available soon.
