### ISSUE TITLE
Perform first release

### ISSUE THREAD

**Issue by gastaldi** [quarkiverse/quarkus-hibernate-types#3]
Please close this issue when the first release is performed. Instructions are available here: https://github.com/quarkiverse/quarkiverse/wiki/Release

Feel free to reach us out if you have any questions. 

Thank you!

**Comment by andrejpetras** [comment]
Release 0.1.0 
https://search.maven.org/search?q=g:io.quarkiverse.hibernatetypes%20AND%20a:quarkus-hibernate-types-parent
