### ISSUE TITLE
Add support for "hibernate-reactive"

### ISSUE THREAD

**Issue by The-Funk** [quarkiverse/quarkus-hibernate-types#80]
I noticed in dependencies for this extension that hibernate-orm is referenced. Does this extension support hibernate-reactive?

I am currently using it in a hibernate-reactive environment and everything appears to be working, however I also have a dependency for hibernate-orm and agroal that are not coming from my other dependencies. I believe the hibernate-orm extension is being added from quarkus-hibernate-types.

FYI: When used in a reactive project, quarkus-hibernate-types adds agroal-pool and hibernate-orm to dependencies.

**Comment by bboyz269** [comment]
I got some problems while building native artifact in project using "quarkus-hibernate-reactive-panache"

> [error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'mysql' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.

Adding "quarkus.datasource.jdbc=false" didn't help. Fortunately, excluding "agroal" and "narayna-jta" dependencies make the problem go away.

*.build.gradle.kts*
```kotlin
configurations.all {
    exclude("io.quarkus", "quarkus-agroal")
    exclude("io.quarkus", "quarkus-agroal-deployment")
    exclude("io.quarkus", "quarkus-narayana-jta")
    exclude("io.quarkus", "quarkus-narayana-jta-deployment")
}
```

**Comment by wglanzer** [comment]
Hi there, 
using the reactive version of hibernate is currently not (really) supported by the underlying framework "hibernate-types".
My knowledge of the reactive version of hibernate is currently very limited too, so I won't be able to add this improvement by now..
I added a new maven module "reactive" on the "hibernate-reactive" branch to showcase the problem in an integrationtest, if anyone is interested to provide the necessary features.

**Comment by wglanzer** [comment]
Since Quarkus 3.0 provides Hibernate 6.2 this extension will no longer be really necessary. 
This means, that the reactive support won't be included anymore in this extension.
