### ISSUE TITLE
How to customize the ObjectMapper

### ISSUE THREAD

**Issue by Thibaud-R** [quarkiverse/quarkus-hibernate-types#81]
Hello,

I'd like to know if there is a way to customize the JacksonMapper used for jsonb type.
(to exclude serialization of null attributes)

I've seen the JacksonMapperProducer, read about [how to do outside Quarkus world](https://vladmihalcea.com/hibernate-types-customize-jackson-objectmapper/) but ...

Thanks !

**Comment by andrejpetras** [comment]
@Thibaud-R try to impl own `JsonMapper`
https://github.com/quarkiverse/quarkus-hibernate-types/blob/b524fa4cc84da97d0e9fb75735c558f3a7419c98/runtime/src/main/java/io/quarkiverse/hibernate/types/json/JsonMapper.java

example in tests: https://github.com/quarkiverse/quarkus-hibernate-types/blob/b524fa4cc84da97d0e9fb75735c558f3a7419c98/deployment/src/test/java/io/quarkiverse/hibernate/types/MyParamMapper.java


the default `JsonMapper` implementation is `JacksonMapper` and `JacksonMapperProducer` which is using the `ObjectMapper` instance define by Quarkus.
https://github.com/quarkiverse/quarkus-hibernate-types/blob/b524fa4cc84da97d0e9fb75735c558f3a7419c98/runtime/src/main/java/io/quarkiverse/hibernate/types/jackson/JacksonMapper.java
https://github.com/quarkiverse/quarkus-hibernate-types/blob/b524fa4cc84da97d0e9fb75735c558f3a7419c98/runtime/src/main/java/io/quarkiverse/hibernate/types/jackson/JacksonMapperProducer.java

**Comment by Thibaud-R** [comment]
Thanks a lot for the response and the tests input !!!

For more details, I just needed to create a new MapperProducer like in the tests :
https://github.com/quarkiverse/quarkus-hibernate-types/blob/b524fa4cc84da97d0e9fb75735c558f3a7419c98/deployment/src/test/java/io/quarkiverse/hibernate/types/MyParamMapperProducer.java
`
@Singleton
public class CustomObjectMapperSupplier
{
	@Produces
	@Singleton
	@Unremovable
	public JsonMapper jsonb(ObjectMapper objectMapper)
	{
		objectMapper.setSerializationInclusion(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL);
		return new JacksonMapper(objectMapper);
	}
}
`
(sorry for the response delay - week off !)

Thibaud
