### ISSUE TITLE
Add a note about this usage with hibernate-reactive 

### ISSUE THREAD

**Issue by rafaeltuelho** [quarkiverse/quarkus-hibernate-types#90]
As explained by @Sanne in this thread: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/quarkus-hibernate-types

> the hibernate-types project isn't meant to be used by Hibernate Reactive. The "types" notion needs to map to vendor specific types that some databases expose in their proprietary JDBC driver, but Hibernate Reactive doesn't use those drivers.

It looks like the `hibernate-types` extension is not intended to be used in reactive scenarios. It would be worth adding a note to the `README.md` highlighting this.

**Comment by Sanne** [comment]
+1 for a note.

Ideally - not sure if that's feasible - an exception with an explanation could be useful too.

**Comment by Sanne** [comment]
Relates to #80

**Comment by wglanzer** [comment]
I added a "limitation" note and quoted your explanation @Sanne.
So I will close this issue, because of #80.
